# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.newtabpage.directory.ping", "");
user_pref("browser.newtabpage.directory.source", "");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.page", 0);
user_pref("browser.urlbar.searchSuggestionsChoice", false);
user_pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.disable_open_during_load", false);
user_pref("dom.disable_window_open_feature.location", false);
user_pref("dom.ipc.plugins.asyncdrawing.enabled", false);
user_pref("dom.ipc.plugins.flash.disable-protected-mode", true);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddon.update.url", "");
user_pref("general.warnOnAboutConfig", false);
user_pref("media.gmp-manager.url", "");
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.stricttransportsecurity.preloadlist", false);
user_pref("plugin.default.state", 2);
user_pref("plugin.scan.plid.all", false);
user_pref("security.OCSP.enabled", 0);
user_pref("security.fileuri.strict_origin_policy", false);
user_pref("security.mixed_content.send_hsts_priming", false);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
